### ISSUE TITLE
PWA don't support yet

### ISSUE THREAD

**Issue by kamkara** [Bertrand-Bichat/pwa-test#6]
![Capture d’écran de 2022-03-10 13-24-51](https://user-images.githubusercontent.com/72747066/157670938-ca3c1c2d-35a6-4029-aabc-0b535aa435a4.png)

**Comment by Bertrand-Bichat** [comment]
> ![Capture d’écran de 2022-03-10 13-24-51](https://user-images.githubusercontent.com/72747066/157670938-ca3c1c2d-35a6-4029-aabc-0b535aa435a4.png)

This is the offline page which appears when internet connection is OFF.  I have just tested the app url and it works for me. Are you sure that your internet connection was ON during your tests ?
